name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs/ -e '
            using Pkg;
            Pkg.add(url = ".."); 
            Pkg.add(url = "https://github.com/JuliaRCM/WassersteinDictionaries.jl/"); 
            '
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using OptimalMappings
            DocMeta.setdocmeta!(OptimalMappings, :DocTestSetup, :(using OptimalMappings); recursive=true)
            doctest(OptimalMappings)'
